# -*- coding: utf-8 -*-
"""Coqui-XTTS-v2-Google-Colab.ipynb

Automatically generated by Colab.
Example script showing all cells from the tutorial.
Replace placeholders with your own values.
"""

!apt-get update -qq
!apt-get install -y python3.11 python3.11-venv python3.11-dev

!python3.11 -m venv /content/py311env
!/content/py311env/bin/pip install --upgrade pip
!/content/py311env/bin/pip install TTS

!/content/py311env/bin/pip install "transformers<4.50.0"
!/content/py311env/bin/pip install torch==2.1.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118

# %%writefile /content/load_model.py
# import os
# os.environ['MPLBACKEND'] = 'Agg'
# from TTS.api import TTS
# import torch
# 
# device = "cuda" if torch.cuda.is_available() else "cpu"
# tts = TTS('tts_models/multilingual/multi-dataset/xtts_v2').to(device)
# print(f'Model loaded on {device}!')

!/content/py311env/bin/python /content/load_model.py

from google.colab import drive
drive.mount('/content/drive')

# %%writefile /content/generate_voice.py
# import os
# os.environ['MPLBACKEND'] = 'Agg'
# from TTS.api import TTS
# import torch
# 
# device = "cuda" if torch.cuda.is_available() else "cpu"
# tts = TTS('tts_models/multilingual/multi-dataset/xtts_v2').to(device)
# 
# # Your text here - replace with whatever you want to generate
# text = "Hey everyone, welcome to the tutorial. This is an example of AI voice cloning."
# 
# # Generate speech - REPLACE 'your_audio_sample.wav' with your actual filename
# tts.tts_to_file(
#     text=text,
#     speaker_wav="/content/drive/MyDrive/your_audio_sample.wav",
#     language="en",
#     file_path="/content/cloned_voice.wav"
# )
# 
# print("Voice generated: /content/cloned_voice.wav")

!/content/py311env/bin/python /content/generate_voice.py

from google.colab import files
files.download("/content/cloned_voice.wav")
